apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nutrilens-ingress
  namespace: nutrilens
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nutrilens-service
            port:
              number: 80
