apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nutrilens-ingress
  namespace: nutrilens
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
  - hosts:
    - nutrilens.duckdns.org
    secretName: nutrilens-tls
  rules:
  - host: nutrilens.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nutrilens-service
            port:
              number: 80
