"""add onboarding tracking

Revision ID: 4c5f18a22d10
Revises: 2974c088b936
Create Date: 2025-10-06 16:35:02.301265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5f18a22d10'
down_revision: Union[str, None] = '2974c088b936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('onboarding_current_step', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('basic_info_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('goal_selection_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('path_selection_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('preferences_completed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('onboarding_started_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
